### ISSUE TITLE
Not able to butcher 1.0

### ISSUE THREAD

**Issue by Nicaara** [Lord-of-the-Rims-DevTeam/Lord-of-the-Rims---The-Third-Age#12]
Using current versions of all mods as of 8/5/18

Can't butcher anything, period.

https://git.io/fNXbC

**Comment by Nicaara** [comment]
Still a problem, now there are problems with the meat textures too apparently? https://git.io/fNMZr

I changed starting scenario to land with salted and raw meat. Salted lorien venison and megasloth meat are pink boxes, regular meat is fine. 
![20180806174014_1](https://user-images.githubusercontent.com/42127397/43744519-fe55ee3a-999f-11e8-94f6-5c26d07ba553.jpg)

**Comment by isacmms** [comment]
So it seems this butchery issue is from Alien Races latest commits. This is not happening with the release version found [here](https://github.com/RimWorld-CCL-Reborn/AlienRaces/releases)

**Comment by Nicaara** [comment]
Fixed
